name: Auto Deployment to S3 bucket

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Build, Deploy to S3 bucket
    runs-on: [ubuntu-latest]
    env:
      working-directory: ./client

    strategy:
      matrix:
        node-version: [16.19.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Npm install
        run: npm install
        working-directory: ${{env.working-directory}}

      - name: Build
        run: npm run build
        working-directory: ${{env.working-directory}}

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_IAM_MANAGER_AKEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_IAM_MANAGER_SKEY }}
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            dist s3://quotesmark